// Static list of the 54 weekly Torah portions (parshiot), with their
// Sefaria verse-range refs. This mapping never changes, so it's baked in
// rather than fetched — only the verse text itself is pulled from Sefaria
// live, per parsha, when the user picks one.
const PARSHIOT = [
  { book: "Genesis", title: "Bereshit", heTitle: "בראשית", wholeRef: "Genesis 1:1-6:8" },
  { book: "Genesis", title: "Noach", heTitle: "נח", wholeRef: "Genesis 6:9-11:32" },
  { book: "Genesis", title: "Lech Lecha", heTitle: "לך לך", wholeRef: "Genesis 12:1-17:27" },
  { book: "Genesis", title: "Vayera", heTitle: "וירא", wholeRef: "Genesis 18:1-22:24" },
  { book: "Genesis", title: "Chayei Sara", heTitle: "חיי שרה", wholeRef: "Genesis 23:1-25:18" },
  { book: "Genesis", title: "Toldot", heTitle: "תולדות", wholeRef: "Genesis 25:19-28:9" },
  { book: "Genesis", title: "Vayetzei", heTitle: "ויצא", wholeRef: "Genesis 28:10-32:3" },
  { book: "Genesis", title: "Vayishlach", heTitle: "וישלח", wholeRef: "Genesis 32:4-36:43" },
  { book: "Genesis", title: "Vayeshev", heTitle: "וישב", wholeRef: "Genesis 37:1-40:23" },
  { book: "Genesis", title: "Miketz", heTitle: "מקץ", wholeRef: "Genesis 41:1-44:17" },
  { book: "Genesis", title: "Vayigash", heTitle: "ויגש", wholeRef: "Genesis 44:18-47:27" },
  { book: "Genesis", title: "Vayechi", heTitle: "ויחי", wholeRef: "Genesis 47:28-50:26" },
  { book: "Exodus", title: "Shemot", heTitle: "שמות", wholeRef: "Exodus 1:1-6:1" },
  { book: "Exodus", title: "Vaera", heTitle: "וארא", wholeRef: "Exodus 6:2-9:35" },
  { book: "Exodus", title: "Bo", heTitle: "בא", wholeRef: "Exodus 10:1-13:16" },
  { book: "Exodus", title: "Beshalach", heTitle: "בשלח", wholeRef: "Exodus 13:17-17:16" },
  { book: "Exodus", title: "Yitro", heTitle: "יתרו", wholeRef: "Exodus 18:1-20:23" },
  { book: "Exodus", title: "Mishpatim", heTitle: "משפטים", wholeRef: "Exodus 21:1-24:18" },
  { book: "Exodus", title: "Terumah", heTitle: "תרומה", wholeRef: "Exodus 25:1-27:19" },
  { book: "Exodus", title: "Tetzaveh", heTitle: "תצוה", wholeRef: "Exodus 27:20-30:10" },
  { book: "Exodus", title: "Ki Tisa", heTitle: "כי תשא", wholeRef: "Exodus 30:11-34:35" },
  { book: "Exodus", title: "Vayakhel", heTitle: "ויקהל", wholeRef: "Exodus 35:1-38:20" },
  { book: "Exodus", title: "Pekudei", heTitle: "פקודי", wholeRef: "Exodus 38:21-40:38" },
  { book: "Leviticus", title: "Vayikra", heTitle: "ויקרא", wholeRef: "Leviticus 1:1-5:26" },
  { book: "Leviticus", title: "Tzav", heTitle: "צו", wholeRef: "Leviticus 6:1-8:36" },
  { book: "Leviticus", title: "Shmini", heTitle: "שמיני", wholeRef: "Leviticus 9:1-11:47" },
  { book: "Leviticus", title: "Tazria", heTitle: "תזריע", wholeRef: "Leviticus 12:1-13:59" },
  { book: "Leviticus", title: "Metzora", heTitle: "מצורע", wholeRef: "Leviticus 14:1-15:33" },
  { book: "Leviticus", title: "Achrei Mot", heTitle: "אחרי מות", wholeRef: "Leviticus 16:1-18:30" },
  { book: "Leviticus", title: "Kedoshim", heTitle: "קדושים", wholeRef: "Leviticus 19:1-20:27" },
  { book: "Leviticus", title: "Emor", heTitle: "אמור", wholeRef: "Leviticus 21:1-24:23" },
  { book: "Leviticus", title: "Behar", heTitle: "בהר", wholeRef: "Leviticus 25:1-26:2" },
  { book: "Leviticus", title: "Bechukotai", heTitle: "בחוקתי", wholeRef: "Leviticus 26:3-27:34" },
  { book: "Numbers", title: "Bamidbar", heTitle: "במדבר", wholeRef: "Numbers 1:1-4:20" },
  { book: "Numbers", title: "Nasso", heTitle: "נשא", wholeRef: "Numbers 4:21-7:89" },
  { book: "Numbers", title: "Beha'alotcha", heTitle: "בהעלותך", wholeRef: "Numbers 8:1-12:16" },
  { book: "Numbers", title: "Sh'lach", heTitle: "שלח", wholeRef: "Numbers 13:1-15:41" },
  { book: "Numbers", title: "Korach", heTitle: "קרח", wholeRef: "Numbers 16:1-18:32" },
  { book: "Numbers", title: "Chukat", heTitle: "חקת", wholeRef: "Numbers 19:1-22:1" },
  { book: "Numbers", title: "Balak", heTitle: "בלק", wholeRef: "Numbers 22:2-25:9" },
  { book: "Numbers", title: "Pinchas", heTitle: "פנחס", wholeRef: "Numbers 25:10-30:1" },
  { book: "Numbers", title: "Matot", heTitle: "מטות", wholeRef: "Numbers 30:2-32:42" },
  { book: "Numbers", title: "Masei", heTitle: "מסעי", wholeRef: "Numbers 33:1-36:13" },
  { book: "Deuteronomy", title: "Devarim", heTitle: "דברים", wholeRef: "Deuteronomy 1:1-3:22" },
  { book: "Deuteronomy", title: "Vaetchanan", heTitle: "ואתחנן", wholeRef: "Deuteronomy 3:23-7:11" },
  { book: "Deuteronomy", title: "Eikev", heTitle: "עקב", wholeRef: "Deuteronomy 7:12-11:25" },
  { book: "Deuteronomy", title: "Re'eh", heTitle: "ראה", wholeRef: "Deuteronomy 11:26-16:17" },
  { book: "Deuteronomy", title: "Shoftim", heTitle: "שופטים", wholeRef: "Deuteronomy 16:18-21:9" },
  { book: "Deuteronomy", title: "Ki Teitzei", heTitle: "כי תצא", wholeRef: "Deuteronomy 21:10-25:19" },
  { book: "Deuteronomy", title: "Ki Tavo", heTitle: "כי תבוא", wholeRef: "Deuteronomy 26:1-29:8" },
  { book: "Deuteronomy", title: "Nitzavim", heTitle: "נצבים", wholeRef: "Deuteronomy 29:9-30:20" },
  { book: "Deuteronomy", title: "Vayeilech", heTitle: "וילך", wholeRef: "Deuteronomy 31:1-30" },
  { book: "Deuteronomy", title: "Ha'Azinu", heTitle: "האזינו", wholeRef: "Deuteronomy 32:1-52" },
  { book: "Deuteronomy", title: "V'Zot HaBerachah", heTitle: "וזאת הברכה", wholeRef: "Deuteronomy 33:1-34:12" },
];
